[build]
  command = "npm run build"
  publish = ".next"
  environment = { NODE_VERSION = "20.11.1" }

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true" 